### ISSUE TITLE
ConnectionReset (os error 10054) on multiple find

### ISSUE THREAD

**Issue by Guillaume-Lebegue** [denodrivers/deno_mongo#165]
Hello,
I'm using deno_mongo v0.20.1 with Deno 1.6.3 on Window 10

And I found an error happening when multiple find are fired at the same time

Here the error
```
error: Uncaught (in promise) ConnectionReset: An existing connection was forcibly closed by the remote host. (os error 10054)
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:98:12)
    at async read (deno:runtime/js/12_io.js:99:19)
    at async BufReader.read (bufio.ts:146:12)
    at async BufReader.readFull (bufio.ts:178:20)
    at async WireProtocol.receive (protocol.ts:79:28)
```

Here code that fire this error on my end:
```
import { MongoClient } from "https://deno.land/x/mongo@v0.20.1/mod.ts";

class DB {
    public client: MongoClient;

    constructor(public dbName: string, public url: string) {
        this.dbName = dbName;
        this.url = url;
        this.client = new MongoClient;
    }

    async connect() {
        await this.client.connect(this.url);
        console.log(`Connected to database ${this.dbName} at url: ${this.url}`);
    }

    get getDatabase() {
        return this.client.database(this.dbName);
    }
}

interface foo {
    _id: {
        $oid: string;
    };
    bar: string;
};

const db = new DB('dbFoo', 'mongodb://127.0.0.1:27017');
await db.connect();
const foos = db.getDatabase.collection<foo>('foos');

const find = async (bar: string) => {
    const foo = await foos.findOne({ bar });

    if (foo)
        return foo;
    
    throw new Error('Not found');
}

const promiseList = [
    find('fooBar'),
    find('fooBar'),
    find('fooBar')
];

const res = await Promise.all(promiseList);
res.forEach(foo => {
    console.log('got foo: ', foo);
})
```

**Comment by MariusVatasoiu** [comment]
I have the same error, also on Windows 10 with Deno 1.7.0. I have a page where I call `findOne` and if I refresh the page multiple times, I get this error.

In 0.1x versions I didn't have this problem, only on 0.2x.

**Comment by Guillaume-Lebegue** [comment]
I have just tried on Linux and I get a different error
```
error: Uncaught (in promise) AssertionError
    throw new AssertionError(msg);
          ^
    at assert (asserts.ts:152:11)
    at WireProtocol.receive (protocol.ts:80:7)
```

**Comment by ameenQ** [comment]
> I have the same error, also on Windows 10 with Deno 1.7.0. I have a page where I call `findOne` and if I refresh the page multiple times, I get this error.
> 
same :(

**Comment by MariusVatasoiu** [comment]
@Guillaume-Lebegue @ameenQ what mongodb version do you use? v3 or v4?

**Comment by Guillaume-Lebegue** [comment]
I'm using MongoDB server version 4.2.8

**Comment by MariusVatasoiu** [comment]
I also have 4.x version. Maybe the driver only works with version. 3.x.
