### ISSUE TITLE
Can Not create Indexes

### ISSUE THREAD

**Issue by zsattari** [denodrivers/deno_mongo#173]
when I create indexes in multiple collection, I get **Assertion Error**
```
error: Uncaught (in promise) AssertionError
    throw new AssertionError(msg);
          ^
    at assert (asserts.ts:170:11)
    at WireProtocol.receive (protocol.ts:80:7)
```

**Comment by Masoumeh-Hashemi** [comment]
I have the same problem with it zahra!
I just can create indexes for one of my collections.

**Comment by manyuanrong** [comment]
Issues with boilerplate code are usually noticed and someone can fix them faster

**Comment by erfanium** [comment]
@manyuanrong Can you provide a repro code? I don't have this problem in my personal project
