### ISSUE TITLE
Getting "Authentication failed" randomly

### ISSUE THREAD

**Issue by dotba** [denodrivers/deno_mongo#174]
I'm getting this error randomly when i try to connect to a cluster
```
error: Uncaught (in promise) Error: MongoError: {"ok":0,"errmsg":"Authentication failed.","code":18,"codeName":"AuthenticationFailed","operationTime":{"$timestamp":"6922424620343623682"},"$clusterTime":{"clusterTime":{"$timestamp":"6922424620343623682"},"signature":{"hash":"XXX","keyId":{"low":1,"high":1602091634,"unsigned":false}}}}
            throw new MongoError(maybeError);
            ^
    at WireProtocol.commandSingle (protocol.ts:34:13)
    at async continueScramConversation (scram.ts:194:18)
    at async executeScram (scram.ts:118:10)
    at async ScramAuthPlugin.auth (scram.ts:59:12)
    at async MongoClient.connect (client.ts:67:7)
```

**Comment by erfanium** [comment]
@4ov Is your problem still exist on newer driver versions? If yes, can you provide a repro?
