### ISSUE TITLE
Mongo Error on Deno runtime

### ISSUE THREAD

**Issue by NaderBhrr** [denodrivers/deno_mongo#177]
Hello
I have tried to run a project on deno, but I receive the following error when trying to run it using "deno"

```javascript
error: Uncaught Error: MongoError: "Connection failed: Connection refused (os error 111)"
        throw new MongoError(`Connection failed: ${e.message || e}`);
              ^
    at MongoClient.connect (client.ts:93:15)
    at async db.ts:5:12

```
### Note:
I have tried it several times but the problem still persists.

Thanks in advance

**Comment by hackers267** [comment]
May I know how do you use it?

**Comment by hackers267** [comment]
May I know how do you use it?

**Comment by ebebbington** [comment]
Expanding upon @hackers267, show your code. It's possible that the hostname/port is incorrect

**Comment by NaderBhrr** [comment]
Thanks for the reply

I have allocated a separate module for database namely db.ts

```javascript

import { MongoClient } from "https://deno.land/x/mongo@v0.21.2/mod.ts";

const client = new MongoClient();
// await client.connect("mongodb://localhost:27017");
const db = await client.connect("mongodb://localhost:27017/kayran");

export * from "https://deno.land/x/mongo@v0.21.2/mod.ts";

export default db;
```

Please note that, I did successfully launched my project but after a few re-run deno stopped creating the server and currently it is showing the above error

Thank you

**Comment by hackers267** [comment]
If you used os is window. Try replace localhost with 127.0.0.1

**Comment by NaderBhrr** [comment]
My OS is "Linux Manjaro" and I can run the project on the "Ubuntu" without any problem

**Comment by borsemayur2** [comment]
Make sure mongo is running by using `sudo service mongodb start` command

**Comment by SenhorBardell** [comment]
Faced the same situation and can confirm that changing `localhost` to `127.0.0.1` solved the issue @NaderBhrr

**Comment by jacoborus** [comment]
> If you used os is window. Try replace localhost with 127.0.0.1

This also solved my problem on Ubuntu

**Comment by jespertheend** [comment]
I have the same problem on ubuntu, but I don't think it's an issue with this driver.
When I run `Deno.connect({hostname: "<domain name of our database", port: 27017})` I'm getting the same os error 111.
Connecting to the ip directly also fixes it for me, and connecting from my local machine to the domain name also works just fine.
It turns out this was caused by ipv6 somehow. When I created a digitalocean droplet without ipv6 support it was able to connect to the server again.
