### ISSUE TITLE
Broken Pipe Error From deno_mongo

### ISSUE THREAD

**Issue by KotadiyaHiral** [denodrivers/deno_mongo#187]
```
0|app      |     at async Collection.findOne (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/collection/collection.ts:43:12)
0|app      | 2021-03-26T06:15:07.234Z [10] BrokenPipe: Broken pipe (os error 32) 
0|app      |     at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
0|app      |     at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
0|app      |     at async write (deno:runtime/js/12_io.js:118:20)
0|app      |     at async Object.writeAll (deno:runtime/js/13_buffer.js:224:19)
0|app      |     at async WireProtocol.command (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/protocol/protocol.ts:55:7)
0|app      |     at async WireProtocol.commandSingle (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/protocol/protocol.ts:31:19)
0|app      |     at async FindCursor.executor (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/collection/commands/find.ts:17:24)
```

I rarely get this error. And can not identify when it occurs. 
This is my deps..
```
export { MongoClient } from "https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/mod.ts"; // Used directly from refactor branch of deno_mongo
export type { Document } from "https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/mod.ts"; // Used directly from refactor branch of deno_mongo
export { ObjectId } from "https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/bson/mod.ts"; // Used directly from refactor branch of deno_mongo
```

**Comment by manyuanrong** [comment]
Thank you for informing you about this problem, but I can’t find any clues from the information given. I’m not sure if the triggered error comes from Deno itself or the driver. I need to continue to observe.

**Comment by KotadiyaHiral** [comment]
Thank you for your instant reply.

**Comment by lucsoft** [comment]
ref https://github.com/denodrivers/deno_mongo/issues/278
