### ISSUE TITLE
Run time assertion error

### ISSUE THREAD

**Issue by KotadiyaHiral** [denodrivers/deno_mongo#189]
```
0|app  | error: Uncaught (in promise) AssertionError
0|app  |     throw new AssertionError(msg);
0|app  |           ^
0|app  |     at assert (https://deno.land/std@0.83.0/testing/asserts.ts:170:11)
0|app  |     at WireProtocol.receive (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/protocol/protocol.ts:80:7)
````
I get this error frequently.

**Comment by manyuanrong** [comment]
What version is it from? Concurrent query requests are not supported before the latest version, and similar errors will occur for concurrent queries

**Comment by KotadiyaHiral** [comment]
deno 1.8.2 (release, x86_64-unknown-linux-gnu)
v8 9.0.257.3
typescript 4.2.2

```
export { MongoClient, Document } from "https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/mod.ts"; // Used directly from refactor branch of deno_mongo
export { ObjectId } from "https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/bson/mod.ts"; // Used directly from refactor branch of deno_mongo
```

**Comment by lucsoft** [comment]
ref https://github.com/denodrivers/deno_mongo/issues/278
