### ISSUE TITLE
connect to MongoDB Atlas Error: MongoError: "Connection failed: failed to lookup address information: nodename nor servname provided, or not known"

### ISSUE THREAD

**Issue by RNR1** [denodrivers/deno_mongo#203]
I am getting an error when trying to login to a MongoDB Atlas DB:

```
Error: MongoError: "Connection failed: failed to lookup address information: nodename nor servname provided, or not known"
    at MongoClient.connect (https://deno.land/x/mongo@v0.23.1/src/client.ts:26:13)
    at async connect (file:///Users/ronbraha/code/projects/road-trip/backend/config/db_client.ts:8:8)
```

specifications:
```
macOS Big Sur Version 11.2.3
deno 1.10.2 (release, x86_64-apple-darwin)
v8 9.1.269.27
typescript 4.2.2
mongo@v0.23.1
```

My code:

```
import { MongoClient } from 'mongo';

let db: ReturnType<MongoClient['database']>;

export async function connect() {
	try {
		db = await new MongoClient().connect({
			db: 'roadTrip',
			tls: true,
			servers: [
				{
					host: 'cluster0.vfygo.mongodb.net',
					port: 27017
				}
			],
			credential: {
				username: 'Ron',
				password: 'Aj8FOtWMhrZMa8Ai',
				mechanism: 'SCRAM-SHA-1'
			}
		});
	} catch (err) {
		console.error(err);
	}
}

export function getDb() {
	return db;
}

```

To clarify, this is the URL I got from the atlas cluster connect:
```
mongodb+srv://Ron:<password>@cluster0.vfygo.mongodb.net/roadTrip?retryWrites=true&w=majority
```

I really appreciate any help you can provide.

**Comment by manyuanrong** [comment]
It seems that there is a problem with your server address, you can directly use uri to connect

![image](https://user-images.githubusercontent.com/7514524/119660418-d46dc180-be61-11eb-88e0-04d91450af40.png)

**Comment by manyuanrong** [comment]
Should be `SCRAM-SHA-1`, not `SCRAM_SHA_1`

**Comment by RNR1** [comment]
Thanks! it worked. 
I will close this issue, but I would recommend referencing this param on the examples because right now, the connect string option hints that it's more compatible with local instances and connecting to an Atlas cluster is a common use case.
