### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by garrigaj** [denodrivers/deno_mongo#206]
I am getting this error when I try to connect:
error: Uncaught (in promise) Error: MongoError: "Connection failed: Invalid hostname: 'cluster0.gpkxo.mongodb.net?retryWrites=true&w=majority'"
        throw new MongoError(`Connection failed: ${e.message || e}`);
              ^
    at MongoClient.connect (https://deno.land/x/mongo@v0.22.0/src/client.ts:93:15)
    at async MongoDBConnector._makeConnection (https://deno.land/x/denodb@v1.0.38/lib/connectors/mongodb-connector.ts:44:7)
    at async MongoDBConnector.query (https://deno.land/x/denodb@v1.0.38/lib/connectors/mongodb-connector.ts:65:5)
    at async Database.query (https://deno.land/x/denodb@v1.0.38/lib/database.ts:240:21)
    at async Function.createTable (https://deno.land/x/denodb@v1.0.38/lib/model.ts:172:5)
    at async Database.sync (https://deno.land/x/denodb@v1.0.38/lib/database.ts:210:7)

I used the code example from the home page:
db: 'todo-app',
    tls: true,
    servers: [
      {
        host: 'cluster0.gpkxo.mongodb.net?retryWrites=true&w=majority',
        port: 27017,
      },
    ],
    credential: {
      username: '<my_username>',
      password: '<my_password>',
      db: 'todo-app',
      mechanism: 'SCRAM-SHA-1',
    },

I also verified that the password was available by resetting and I made sure I had whitelisted my IP address.

**Comment by manyuanrong** [comment]
Try to connect using URI

**Comment by garrigaj** [comment]
I did and got the same error message.

**Comment by manyuanrong** [comment]
There is a problem with the domain name resolution. Are you sure your domain name is correct? Can you connect through other client tools?

**Comment by garrigaj** [comment]
I connect with Mongoose on Node.js using the full URI without issues. When I use either the full URI or the more detailed method here, I can't connect.

**Comment by manyuanrong** [comment]
host should only contains cluster0.gpkxo.mongodb.net

**Comment by garrigaj** [comment]
Tried it. It still didn’t work. I also tried with and without the Mongo protocol and still could not connect.

**Comment by manyuanrong** [comment]
I don't know what you tried and whether you constructed the parameters correctly. Just believe that you did the right thing. By the way, can your domain name be resolved successfully through `ping` or `route`?
(give me the result of your attempt)

**Comment by garrigaj** [comment]
I can connect with Mongoose, MongoDB Compass, and Node.js MongoDB driver with the URI. I cannot connect with this library.

**Comment by manyuanrong** [comment]
Perhaps your database is on an internal network. You can give me the results of your investigation. Like this,
![image](https://user-images.githubusercontent.com/7514524/121119986-43c6b680-c84f-11eb-9697-6c2217653018.png)

**Comment by garrigaj** [comment]
That is the URI MongoDB Atlas gives me. Everything, except this driver, that I use to connect to it works: mongo+srv://<username>:<password>@cluster0.gpkxo.mongodb.net/<db_name>?retryWrites=true&w=majority

**Comment by RNR1** [comment]
What made it possible for me to connect via URI is adding the "authMechanism" param exactly like shown below. I also added it to the docs here a few weeks ago.
```
await client.connect(
  "mongodb+srv://<username>:<password>@<db_cluster_url>/<db_name>?authMechanism=SCRAM-SHA-1",
);
```

**Comment by acaala** [comment]
Hi, i'm having a similar issue.

`Error: MongoError: "Connection failed: failed to lookup address information: No address associated with hostname"`

I tried both methods on the docs but result in the same issue.
I can connect to the db with node so i know the hostname is right.

**Comment by PeterKitonga** [comment]
If anyone is still having an issue with this, try connecting through a specific shard in your cluster. I got a successful connection by setting the host to `nodejs-shard-00-01.j6dzr.mongodb.net`. Notice the shard `-shard-00-01` in the string. I could be wrong but it works for me.

**Comment by GlennGuegan** [comment]
Hello 🙂
If you use Mongo Atlas you should add your IP public address as available in Network Access section

**Comment by toridoriv** [comment]
> What made it possible for me to connect via URI is adding the "authMechanism" param exactly like shown below. I also added it to the docs here a few weeks ago.
> 
> ```
> await client.connect(
>   "mongodb+srv://<username>:<password>@<db_cluster_url>/<db_name>?authMechanism=SCRAM-SHA-1",
> );
> ```

Thanks! This worked perfectly 💜

**Comment by marcelovicentegc** [comment]
> What made it possible for me to connect via URI is adding the "authMechanism" param exactly like shown below. I also added it to the docs here a few weeks ago.
> 
> ```
> await client.connect(
>   "mongodb+srv://<username>:<password>@<db_cluster_url>/<db_name>?authMechanism=SCRAM-SHA-1",
> );
> ```

Just for the record. I was also facing this issue and adding the `authMechanism` solved the problem.
