### ISSUE TITLE
Error: MongoError: "Connection failed: failed to lookup address information: No address associated with hostname"

### ISSUE THREAD

**Issue by JoRios1006** [denodrivers/deno_mongo#217]
I tried connecting to Mongo Atlas and I only get this error.
`Error: MongoError: "Connection failed: failed to lookup address information: No address associated with hostname"`
I tried to connect to Mongo on node and works flawlessly.

**Comment by JoRios1006** [comment]
I give up trying to connect to Mongo Atlas, create a VM and **NOW THIS ERROR**

```
Uncaught (in promise) AssertionError
    throw new AssertionError(msg);
          ^
    at assert (https://deno.land/std@0.83.0/testing/asserts.ts:170:11)
    at WireProtocol.receive (https://deno.land/x/mongo@v0.23.1/src/protocol/protocol.ts:104:7)
```
**_### W H Y_**

**Comment by GlennGuegan** [comment]
Hello 🙂
I agree with you, I spent many times to trying to connect Mongo Atlas to my Deno project. 
Check if your public IP address is available at Mongo Atlas.
The format string to connecting Mongo Atlas is : 
```
connect("mongodb+srv://<USER>:<PASSWORD>@<ATLAS_CLUSTER>.mongodb.net/<DB_NAME>?authMechanism=SCRAM-SHA-1")
``` 
You can find address in your dashboard  on Mongo Atlas
