### ISSUE TITLE
quits unexpectedly 

### ISSUE THREAD

**Issue by mass1023** [denodrivers/deno_mongo#227]
the code quits unexpectedly giving this error:
```

Uncaught (in promise) ConnectionReset: Connection reset by peer (os error 104)
      rr = await this.rd.read(this.buf);

at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async read (deno:extensions/net/01_net.js:21:19)
    at async BufReader.read (https://deno.land/std@0.99.0/io/bufio.ts:148:12)
    at async BufReader.readFull (https://deno.land/std@0.99.0/io/bufio.ts:180:20)
    at async WireProtocol.receive (https://deno.land/x/mongo@v0.24.0/src/protocol/protocol.ts:103:28)
```

**Comment by erfanium** [comment]
duplicated issue
