### ISSUE TITLE
conflict between deno-mongo v0.25.0 and mongo version v5.0

### ISSUE THREAD

**Issue by Masoumeh-Hashemi** [denodrivers/deno_mongo#243]
when I  updated deno mongo to new versin **v0.25.0**
and my mongo version is  **v5.0.2** 
I face an error, here is the error

`error: Uncaught (in promise) Error: MongoError: {"ok":0,"errmsg":"BSON field 'listCollections.batchSize' is an unknown field.","code":40415,"codeName":"Location40415"}
      throw new MongoError(maybeError);
            ^
    at WireProtocol.commandSingle (https://deno.land/x/mongo@v0.25.0/src/protocol/protocol.ts:38:13)
    at async CommandCursor.<anonymous> (https://deno.land/x/mongo@v0.25.0/src/database.ts:48:28)
    at async CommandCursor.execute (https://deno.land/x/mongo@v0.25.0/src/protocol/cursor.ts:34:21)
    at async CommandCursor.next (https://deno.land/x/mongo@v0.25.0/src/protocol/cursor.ts:48:7)
    at async CommandCursor.[Symbol.asyncIterator] (https://deno.land/x/mongo@v0.25.0/src/protocol/cursor.ts:67:21)
    at async Database.listCollectionNames (https://deno.land/x/mongo@v0.25.0/src/database.ts:75:22)
    at async handleFakeDb (file:///home/etefaghian/Desktop/work/newKaryan/packages/server/src/utils/bootstrap/initializeDB.ts:76:20)
    at async file:///.../packages/server/mod.ts:17:38`

by downgrading my mongo to v4.0 eveything works fine,
so the new deno-mongo v.25 is having a conflict with mongo v.5
thanks for considering this issue and waiting for deno mongo team to solve it...

**Comment by erfanium** [comment]
There's some known issue with mongo v5

**Comment by manyuanrong** [comment]
Close this issue and transfer to this issue tracking: #244
