### ISSUE TITLE
Error: MongoError: {"ok":0,"errmsg":"unallowed argument in listCollections command: batchSize","code":8000,"codeName":"AtlasError"}

### ISSUE THREAD

**Issue by buttercubz** [denodrivers/deno_mongo#244]
i am trying to connect to a cluster in mongodb atlas and i am getting this error.

researching in mongodb documentation I found this https://docs.mongodb.com/v5.0/reference/method/cursor.batchSize/#mongodb-method-cursor.batchSize

and notice that the batch size is 1:
https://deno.land/x/mongo@v0.25.0/src/database.ts#L53

```console
error: Uncaught (in promise) Error: MongoError: {"ok":0,"errmsg":"unallowed argument in listCollections command: batchSize","code":8000,"codeName":"AtlasError"}
      throw new MongoError(maybeError);
            ^
    at WireProtocol.commandSingle (https://deno.land/x/mongo@v0.25.0/src/protocol/protocol.ts:38:13)
    at async CommandCursor.<anonymous> (https://deno.land/x/mongo@v0.25.0/src/database.ts:48:23)
    at async CommandCursor.execute (https://deno.land/x/mongo@v0.25.0/src/protocol/cursor.ts:34:18)
    at async CommandCursor.next (https://deno.land/x/mongo@v0.25.0/src/protocol/cursor.ts:47:27)
    at async CommandCursor.[Symbol.asyncIterator] (https://deno.land/x/mongo@v0.25.0/src/protocol/cursor.ts:67:18)
    at async Database.listCollectionNames (https://deno.land/x/mongo@v0.25.0/src/database.ts:75:22)
    at async ReactiveCore (file:///C:/Users/User/Desktop/reactivedb/src/core/mod.ts:63:28)
    at async file:///C:/Users/User/Desktop/reactivedb/main.ts:1:40
```

![image](https://user-images.githubusercontent.com/47539192/132142206-aa684c8c-f5b4-450f-8616-6141a5a3f011.png)

**Comment by buttercubz** [comment]
ok I think I found it, apparently the batchSize field is no longer needed in the listCollections command in my local copy, removing this field made it work

https://github.com/denodrivers/deno_mongo/blob/588f1c500a210ec6feabc61eab13c0bb36669e65/src/database.ts#L50
