### ISSUE TITLE
Bug with connecting 

### ISSUE THREAD

**Issue by ThatGuyJamal** [denodrivers/deno_mongo#253]
I found 3 errors when running the packages:
```
error: TS2339 [ERROR]: Property 'resolveDns' does not exist on type 'typeof Deno'. 'Deno.resolveDns' is an unstable API. Did you forget to run with the '--unstable' flag?
  resolveDns: typeof Deno.resolveDns;
                          ~~~~~~~~~~
    at https://deno.land/x/mongo@v0.24.0/src/utils/srv.ts:15:27

TS2339 [ERROR]: Property 'resolveDns' does not exist on type 'typeof Deno'. 'Deno.resolveDns' is an unstable API. Did you forget to run with the '--unstable' flag?
  constructor(resolver = { resolveDns: Deno.resolveDns }) {
                                            ~~~~~~~~~~
    at https://deno.land/x/mongo@v0.24.0/src/utils/srv.ts:39:45

TS7006 [ERROR]: Parameter 'record' implicitly has an 'any' type.
    const servers = srvRecord.map((record) => {
                                   ~~~~~~
    at https://deno.land/x/mongo@v0.24.0/src/utils/srv.ts:86:36

Found 3 errors.
```
Code Used:
```ts
import { configs } from "../src/configs.ts"; // link to mongoose connection URL (string)
import { mongoose } from "./deps.ts" 


// deno run --allow-read mod.ts

const client = new mongoose.MongoClient();

await client.connect(configs.mongodb.url);
```
deps.ts
```ts
export * as mongoose from "https://deno.land/x/mongo@v0.24.0/mod.ts";
```

Mongo will not even start.

**Comment by erfanium** [comment]
enable unstable API
