### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by ThatGuyJamal** [denodrivers/deno_mongo#257]
I don't understand what this error is telling me...
```
error: Uncaught AssertionError
    throw new AssertionError(msg);
          ^
    at assert (https://deno.land/std@0.105.0/testing/asserts.ts:217:11)
    at MongoClient.database (https://deno.land/x/mongo@v0.26.0/src/client.ts:67:5)
    at file:///C:/Users/thatguyjamal/.../mongodb/mod.ts:13:43
```
Code:
```ts
// mongoDeno
// export * as mongoDeno from "https://deno.land/x/mongo@v0.26.0/mod.ts";

import { mongoDeno } from "../../deps.ts";
import { configs } from "../../src/configs.ts";

const mongoClient = new mongoDeno.MongoClient();
export interface guildSchemaTypes {
  _id: string;
  settings: Object;
}

export const database = await mongoClient.database("succubus");
export const guildSchema = await database.collection<guildSchemaTypes>("succubus-settings");

export async function init(): Promise<void> {
  await mongoClient.connect({
    db: configs.mongodb.db,
    tls: true,
    servers: [
      {
        host: configs.mongodb.servers.host,
        port: configs.mongodb.servers.port,
      },
    ],
    credential: {
      username: configs.mongodb.credential.username,
      password: configs.mongodb.credential.password,
      db: configs.mongodb.credential.db,
      mechanism: "SCRAM-SHA-1",
    },
  });
}

await init()

const insertId = await guildSchema.insertOne({
  _id: "0",
  settings: {
    name: "test-user",
  },
});
// findOne
const data = await guildSchema.findOne({ _id: insertId });

await console.log(data);
```
This is line 13 from the err
```ts
export const guildSchema = await database.collection<guildSchemaTypes>("succubus-settings");
```

**Comment by erfanium** [comment]
You should init the connection before this line:
```ts
export const database = await mongoClient.database("succubus");
```
