### ISSUE TITLE
feat: better error message when client is not connected

### ISSUE THREAD

**Issue by goodmanworld** [denodrivers/deno_mongo#270]
I do get the following error:

```
error: Uncaught (in promise) AssertionError
    throw new AssertionError(msg);
          ^
    at assert (https://deno.land/std@0.107.0/testing/asserts.ts:224:11)
    at MongoClient.database (https://deno.land/x/mongo@v0.27.0/src/client.ts:67:5)
    at file:///C:/Users/m/NewP/app_back/mongo.ts:6:19

```
And this is my `mongo.ts` code:
```

import { MongoClient } from "./deps.ts";

const client = new MongoClient();
client.connect(Deno.env.get("MONGODB_URI") || "");

const db = client.database(Deno.env.get("DB_NAME") || "");
export default db;

export const userCollection = db.collection("users");
export const surveyCollection = db.collection("surveys");
export const questionCollection = db.collection("questions");
export const answerCollection = db.collection("answers");

```

**Comment by erfanium** [comment]
You should put `await` keyword before `client.connect`

**Comment by goodmanworld** [comment]
> You should put `await` keyword before `client.connect`

Thank you! I did what you said and got a new error:
```

error: Uncaught (in promise) Error: MongoError: "Connection failed: No connection could be made because the target machine actively refused it. (os error 10061)"
      throw new MongoDriverError(`Connection failed: ${e.message || e}`);
            ^
    at MongoClient.connect (https://deno.land/x/mongo@v0.27.0/src/client.ts:41:13)
    at async file:///C:/Users/m/app_back/mongo.ts:4:1
```
