### ISSUE TITLE
Crash on Deno Deploy: Connection reset by peer

### ISSUE THREAD

**Issue by erfanium** [denodrivers/deno_mongo#323]
```
ConnectionReset: Connection reset by peer (os error 104)     
at async read (deno:ext/net/01_net.js:21:19)     
at async BufReader.read (https://deno.land/std@0.118.0/io/buffer.ts:314:18)     
at async BufReader.readFull (https://deno.land/std@0.118.0/io/buffer.ts:343:28)     
at async WireProtocol.receive (https://deno.land/x/mongo@v0.29.0/src/protocol/protocol.ts:77:34)
```

**Comment by jtoppine** [comment]
Same error in Deno 1.20.3, mongo 0.30.0 (not deploy, regular Ubuntu server)
`
error: Uncaught (in promise) ConnectionReset: Connection reset by peer (os error 104)
      rr = await this.#rd.read(this.#buf);
           ^
    at async read (deno:ext/net/01_net.js:24:19)
    at async BufReader.read (https://deno.land/std@0.140.0/io/buffer.ts:383:12)
    at async BufReader.readFull (https://deno.land/std@0.140.0/io/buffer.ts:415:20)
    at async WireProtocol.receive (https://deno.land/x/mongo@v0.30.0/src/protocol/protocol.ts:110:28)
`
Maybe automatic reconnect could handle these situations, if we ever get those? https://github.com/denodrivers/deno_mongo/issues/278

**Comment by FinlayDaG33k** [comment]
Same here on Docker (using the `denoland/deno:ubuntu-1.24.0` image and the Mongo `5.0.6` docker image on the same host.
```
error: Uncaught (in promise) ConnectionReset: Connection reset by peer (os error 104)
      rr = await this.#rd.read(this.#buf);
           ^
    at async read (deno:ext/net/01_net.js:28:19)
    at async BufReader.read (https://deno.land/std@0.136.0/io/buffer.ts:383:12)
    at async BufReader.readFull (https://deno.land/std@0.136.0/io/buffer.ts:415:20)
    at async WireProtocol.receive (https://deno.land/x/mongo@v0.29.4/src/protocol/protocol.ts:110:28)
    ```

**Comment by FinlayDaG33k** [comment]
I did manage to "circumvent" this issue for now by having [my app](https://gitlab.com/FinlayDaG33k/yukikaze/-/commit/931b3dc67ca8e667cc9a72c770b9f176a7c87837) make a small query every 5 seconds (might want to increase this but it'll do for now), keeping the connection alive.  
Because I use [DangoDB](https://github.com/oslabs-beta/dangoDB) and am not very knowledgeable on MongoDB, this was the easiest way for me to accomplish it for me.  
A better solution will need to be built.  

I don't know how this will affect users of `Deno Deploy` since I am not familiar with the service.

**Comment by jespertheend** [comment]
While developing locally I'm connecting to a remote mongo instance, and I am getting this when I close my laptop lid for a while.
For the time being my workaround is this
```js
globalThis.addEventListener("unhandledrejection", e => {
	const err = e.reason;
	if (err instanceof Deno.errors.ConnectionReset || err instanceof Deno.errors.BrokenPipe) {
		if (err.stack?.includes("https://deno.land/x/mongo")) {
			console.warn("Database connection has been lost, restart the dev script in order to reconnect the database.");
			e.preventDefault();
		}
	}
});
```
The database connection stays broken but at least my development script doesn't crash.

**Comment by manyuanrong** [comment]
This is indeed a problem with keepalive, which also exists in other database drivers of deno. I have recently used redis and pgsql in a production environment. Sending heartbeat requests regularly is simple and effective. Of course, this should also be added as a feature of the driver library.
