### ISSUE TITLE
Connecting to a Mongo Atlas serverless cluster gives a LoadBalancerSupportMismatch error

### ISSUE THREAD

**Issue by justinmchase** [denodrivers/deno_mongo#329]
Using a non-serverless cluster it works just fine.

Example connection string:
> mongodb+srv://admin:<pass>@serverlessinstance0.57azg.mongodb.net/example?authMechanism=SCRAM-SHA-1

> error: Uncaught (in promise) Error: MongoError: "Connection failed: MongoError: {\"ok\":0,\"errmsg\":\"The server is being accessed through a load balancer, but this driver does not have load balancing enabled\",\"code\":354,\"codeName\":\"LoadBalancerSupportMismatch\"}"
>      throw new MongoDriverError(`Connection failed: ${e.message || e}`);
>           ^
>    at MongoClient.connect (https://deno.land/x/mongo@v0.29.1/src/client.ts:48:13)
>    at async MongoService.init (file:///home/justin/code/example/src/services/mongo.service.ts:20:15)
>    at async initServices (file:///home/justin/code/example/src/services/mod.ts:17:3)
>    at async file:///home/justin/code/example/index.ts:9:18

**Comment by erfanium** [comment]
`Load Balancer` is not implemented yet
