### ISSUE TITLE
Error on Atlas: not primary and secondaryOk=false

### ISSUE THREAD

**Issue by erfanium** [denodrivers/deno_mongo#333]
```
Error - MongoError: {"topologyVersion":{"processId":"620ab5c7dea2e48072aff8bd","counter":3},"operationTime":{"$timestamp":"7064746775537516821"},"ok":0,"errmsg":"not primary and secondaryOk=false","code":13435,"codeName":"NotPrimaryNoSecondaryOk","$clusterTime":{"clusterTime":{"$timestamp":"7064746775537516821"},"signature":{"hash":"2pB18NeqyGGCrifDhThwCWzt1Sw=","keyId":{"high":1632770001,"low":1,"unsigned":false}}}}
--
34 | Error on find 29793769 Error: MongoError: {"topologyVersion":{"processId":"620ab5c7dea2e48072aff8bd","counter":3},"operationTime":{"$timestamp":"7064746775537516821"},"ok":0,"errmsg":"not primary and secondaryOk=false","code":13435,"codeName":"NotPrimaryNoSecondaryOk","$clusterTime":{"clusterTime":{"$timestamp":"7064746775537516821"},"signature":{"hash":"2pB18NeqyGGCrifDhThwCWzt1Sw=","keyId":{"high":1632770001,"low":1,"unsigned":false}}}}     at WireProtocol.commandSingle (https://deno.land/x/mongo@v0.29.0/src/protocol/protocol.ts:25:19)     at async FindCursor.executor (https://deno.land/x/mongo@v0.29.0/src/collection/commands/find.ts:6:29)     at async FindCursor.execute (https://deno.land/x/mongo@v0.29.0/src/protocol/cursor.ts:17:25)     at async FindCursor.next (https://deno.land/x/mongo@v0.29.0/src/protocol/cursor.ts:29:13)     at async FindCursor.[Symbol.asyncIterator] (https://deno.land/x/mongo@v0.29.0/src/protocol/cursor.ts:45:27)     at async FindCursor.map (https://deno.land/x/mongo@v0.29.0/src/protocol/cursor.ts:62:26)     at async file:///src/main.ts:20:23     at async dispatch (https://deno.land/x/oak@v10.0.0/middleware.ts:16:13)     at async dispatch (https://deno.land/x/oak@v10.0.0/middleware.ts:16:13)     at async dispatch (https://deno.land/x/oak@v10.0.0/middleware.ts:16:13)


```

**Comment by J053Fabi0** [comment]
This happened to me today. I solved it by restarting the program. I'm not sure what caused it.
